In [1]:
class env():
    def __init__(self,ls):
        self.seq = ls
        self.ac = -1
        self.len = len(self.seq)
        self.is_three = False
    def walk(self,action=1):
        done =False
        try:
            prev_ac = self.ac
            self.ac += action
            reward = action*self.seq[self.ac]
            state = self.seq[self.ac]
            current_index = self.seq.index(state)
        except : 
            state = self.seq[prev_ac]
            self.ac = prev_ac
            reward = -20
            current_index = self.seq.index(state)
        
        if self.is_three and action == 3:
            state = self.seq[prev_ac]
            self.ac = prev_ac
            reward = -20
            current_index = self.seq.index(state)
            
        if action == 3:
            self.is_three =True
        if self.len-1== current_index:
            done =True
        yield state,reward,current_index,done
    def reset(self):
        self.seq = ls
        self.ac = -1
        self.is_three = False
        return 0

In [2]:
import numpy as np

In [3]:
def generating_episodes(env,Q,i):
    episode = []
    state = env.reset()
    is_three = False
    current_index = 0
    while True:
        action= get_action(Q[state],i)
        new_state,reward,current_index,done=list(hopping_stone.walk(action))[0] 
        episode.append((state,reward,current_index,action))
        state = new_state
        if done :
            break
    return episode
        

In [4]:
def get_action(Q,i):
    epsilon = 0.7/i    
    action_space = (np.zeros(3)+1)*epsilon/3
    action_space[np.argmax(Q)] = 1 - epsilon + epsilon/3
    action = np.random.choice(np.arange(3)+1,p=action_space)
    return action
        
        
    

In [5]:
import sys
def mc_prediction_q(env, num_episodes, generate_episode, gamma=1.0):
    # initialize empty dictionaries of arrays
    returns_sum = defaultdict(lambda: np.zeros(3))
    N = defaultdict(lambda: np.zeros(3))
    Q = defaultdict(lambda: np.zeros(3))
    
    # loop over episodes
    for i_episode in range(1, num_episodes+1):
        # monitor progress
        if i_episode % 1000 == 0:
            print("\rEpisode {}/{}.".format(i_episode, num_episodes), end="")
            sys.stdout.flush()
        
        ## TODO: complete the function
        temp_list = []
        episode= generating_episodes(env,Q,i_episode)
        for i,exp_tuple in enumerate(episode):
            ## state,reward,current_index,action
            state,_,_,action = exp_tuple
            N[state][action-1] += 1.0 
            for j,exp_tuple2 in enumerate(episode[i:]):
                _,reward,_,_ = exp_tuple2
                ## makes sure it's a single visit.
                if (state,action) not in temp_list:
                    returns_sum[state][action-1] += reward * (gamma ** j)
            Q[state][action-1] = returns_sum[state][action-1]/ N[state][action-1]
            temp_list.append((state,action))         
        
    return Q

In [7]:
from collections import defaultdict
ls= [13,26,90,12,5,20]
hopping_stone = env(ls)
Q= mc_prediction_q(hopping_stone, 5000, generating_episodes)

Episode 5000/5000.

In [8]:
Q

defaultdict(<function __main__.mc_prediction_q.<locals>.<lambda>()>,
            {0: array([169.83333333, 179.        , 321.87239583]),
             13: array([156.83333333,   0.        ,   0.        ]),
             26: array([129.875,   0.   ,   0.   ]),
             90: array([51.87394958, 30.        , 22.        ]),
             12: array([24.47368421, 40.        , 20.        ]),
             5: array([20.,  0.,  0.])})

In [9]:
ls= [13,26,90,12,5,20]
hopping_stone = env(ls)
action = np.argmax(Q[0])+1
r = 0
while True:
    new_state,reward,current_index,done=list(hopping_stone.walk(action))[0]
    r += reward
    action = np.argmax(Q[new_state])+1
    if done :
        break
print(r)

322


In [162]:
90*3 + 12*1 +  20*2

322

In [200]:
index = [(i,(np.argmax(Q[i])+1)) for i in ls]
print(index)
ls=[0]+ [13,26,90,12,5,20]

[(13, 1), (26, 1), (90, 1), (12, 2), (5, 1), (20, 1)]


In [201]:
index = [(np.argmax(Q[i])+1) for i in ls]
ins = np.argmax(Q[0])+1
k = ins
r = []
t = 0 
while True:
    if t != 0:
        ins += k
    r.append(k*ls[ins])
    k = np.argmax(Q[ls[ins]])+1
    t =1
    if ins == len(ls)-1:
        break
    
print(sum(r))    

322


In [216]:
Q

defaultdict(<function __main__.mc_prediction_q.<locals>.<lambda>()>,
            {0: array([  0.        , 176.04433498, 321.99870738]),
             26: array([141.87341772,  61.44444444,   0.        ]),
             12: array([22.5, 40. , 20. ]),
             5: array([20.,  0.,  0.]),
             90: array([51.9991496, 30.       , 32.       ]),
             13: array([0., 0., 0.]),
             20: array([0., 0., 0.])})

In [245]:
ls= [13,26,90,12,5,20]
hopping_stone = env(ls)
action = np.argmax(Q[0])+1
r = 0
while True:
    new_state,reward,current_index,done=list(hopping_stone.walk(action))[0]
    r += reward
    action = np.argmax(Q[new_state])+1
    if done :
        break
print(r)

322


In [68]:
from collections import defaultdict
Q = defaultdict(lambda:np.zero(5))
for i in range(5):
    print(generating_episodes(hopping_stone,Q))

[(0, 57, 2, 3), (19, 12, 3, 1), (12, 5, 4, 1), (5, 20, 5, 1)]
[(0, 57, 2, 3), (19, 12, 3, 1), (12, 5, 4, 1), (5, 20, 5, 1)]
[(0, 13, 0, 1), (13, 26, 1, 1), (26, 15, 4, 3), (5, -20, 4, 3), (5, -20, 4, 2), (5, 20, 5, 1)]
[(0, 52, 1, 2), (26, 15, 4, 3), (5, -20, 4, 3), (5, 20, 5, 1)]
[(0, 52, 1, 2), (26, 15, 4, 3), (5, -20, 4, 3), (5, 20, 5, 1)]


In [16]:

temp = {}
matrix = np.array([[1,2,3],[2,3,4],[3,4,1]])
print(matrix)
flag=0
nrow ,ncol = matrix.shape
for i in range(nrow):
    for j in range(ncol):
        #print(matrix[i][j])
        if i+j != ncol and i+j != 0:
            if i+j not in temp.keys():
                temp[i+j] = [matrix[i][j]]
            else :
                if temp[i+j][-1] != matrix[i][j]:
                    print("\nNot the required matrix!!")
                    flag = 1
                    break
if flag == 0: print("Hankle matrix") 

[[1 2 3]
 [2 3 4]
 [3 4 1]]
Hankle matrix


In [71]:
np.array(matrix)

array([[1, 2, 3],
       [2, 3, 5]])

In [68]:
temp

{1: [2, 2], 2: [3, 3]}

In [100]:
26*2 + 19 +20*3

131

In [210]:
np.array([[1,2,3],[2,3,4],[3,4,1]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 1]])